#!/bin/bash

# No salt is needed for decryption.
# GITENCRYPT_PASS_FIXED=<your-passphrase>

. ~/gitencrypt/base_script

# Error messages are redirect to /dev/null.
$GITENCRYPT_OPEN_SSL_COMMMAND -d -in "$1" 2> /dev/null || cat "$1"

